name: Build and Upload the pip package and Deploy the docker image
on:
  release:
    types:
      - released


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build pip package
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: $
          TWINE_PASSWORD: $
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

  build-docker:
    name: Build Docker container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: build
        name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ format('{0}/{1}:{2}', secrets.DOCKER_USERNAME, steps.ref.outputs.repo-name, github.event.release.tag_name) }}
          push: true
          load: true
          build-args: READONLY_API_TOKEN_GITHUB=${{ secrets.READONLY_API_TOKEN_GITHUB }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  report-if-failed:
    name: Report if workflow failed
    runs-on: ubuntu-latest
    needs: [build, build-docker]
    if: failure() && github.ref == 'refs/heads/master'
    steps:
      - id: send-to-slack
        name: Send failure notification to Slack on failure
        env:
          SLACK_BOT_TOKEN: ${{ secrets.WORKFLOW_STATUS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: workflow-failures
          status: FAILED
          color: danger