name: Lint python code
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint python code
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'

      - id: black
        name: Black code formatter
        uses: psf/black@stable

      - id: flake8
        name: Use flake8 linting
        uses: py-actions/flake8@v2

      - uses: jamescurtin/isort-action@master
        with:
          configuration: "--profile=black"