name: Build and Upload the pip package and Deploy the docker image
on:
  push:
    branches:
      - "docker-image-from-source"
  pull_request:
    branches:
      - "docker-image-from-source"

jobs:
  build-docker:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v3

      - id: setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: build
        name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ format('{0}/programmatic-interface:{1}', secrets.DOCKER_USERNAME, '0.0.27') }}
          push: true

  report-if-failed:
    name: Report if workflow failed
    runs-on: ubuntu-latest
    needs: build-docker
    if: failure() && github.ref == 'refs/heads/master'
    steps:
      - id: send-to-slack
        name: Send failure notification to Slack on failure
        env:
          SLACK_BOT_TOKEN: ${{ secrets.WORKFLOW_STATUS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: workflow-failures
          status: FAILED
          color: danger